modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"
[[mods]]
modId="speakermod"
version="${file.jarVersion}"
displayName="Wireless Speakers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wireless-speakers"
updateJSONURL="https://github.com/mactso/SpeakerMod/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Speaker Mod.'
[[dependencies.speakermod]]
    modId="forge"
    mandatory=true
    versionRange="[5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.speakermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
